# Configuración de Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Metadata del mod
mod_id=dmzkiaspects
mod_name=DMZ Ki Aspects
mod_version=0.1.0-phase1
mod_group_id=com.brochacho.dmzkiaspects
mod_authors=Brochacho
mod_description=Sistema de los 5 Aspectos del Ki para DragonMineZ.

# Versiones (deben coincidir con las que usa DragonMineZ 2.1.3)
minecraft_version=1.20.1
forge_version=47.4.0
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
